import type { PresetItem } from '@ket/preset';

import { writes } from '@ket/preset';

export const WEB_PRESET: PresetItem = {
  $schema: 'https://ui.shadcn.com/schema/registry-item.json',
  name: 'ket-web',
  type: 'registry:item',
  title: 'ket web',
  description:
    'A TanStack Start application under ket, with the gate chain ket runs against itself.',
  dependencies: [
    '@tanstack/react-router@1.170.18',
    '@tanstack/react-start@1.168.34',
    'react@19.2.8',
    'react-dom@19.2.8',
  ],
  devDependencies: [
    'oxlint@1.76.0',
    'oxfmt@0.61.0',
    '@stylistic/eslint-plugin@5.10.0',
    'oxlint-tsgolint@7.0.2001',
    'vite@8.2.0',
    '@vitejs/plugin-react@6.0.5',
    'vitest@4.1.10',
    'fast-check@4.5.0',
    '@playwright/test@1.62.1',
    '@stryker-mutator/core@9.6.1',
    '@stryker-mutator/vitest-runner@9.6.1',
    'steiger@0.6.0',
    '@feature-sliced/steiger-plugin@0.7.0',
    '@steiger/toolkit@0.2.3',
    'knip@6.29.0',
    'jscpd@5.0.14',
    'cspell@10.0.1',
    'lefthook@2.1.10',
    '@commitlint/cli@21.2.1',
    '@commitlint/config-conventional@21.2.0',
    '@nizos/probity@1.10.0',
    'typescript@5.9.3',
    '@types/react@19.2.18',
    '@types/react-dom@19.2.4',
  ],
  files: [
    writes('oxlintrc.json', '.oxlintrc.json'),
    writes('oxfmtrc.json', '.oxfmtrc.json'),
    writes('tsconfig.json', 'tsconfig.json'),
    writes('vite.config.ts', 'vite.config.ts'),
    writes('vitest.config.ts', 'vitest.config.ts'),
    writes('playwright.config.ts', 'playwright.config.ts'),
    writes('stryker.conf.json', 'stryker.conf.json'),
    writes('vitest.mutation.config.ts', 'vitest.mutation.config.ts'),
    writes('steiger.config.ts', 'steiger.config.ts'),
    writes('knip.json', 'knip.json'),
    writes('jscpd.json', '.jscpd.json'),
    writes('cspell.json', 'cspell.json'),
    writes('cspell-words.txt', 'cspell-words.txt'),
    writes('lefthook.yml', 'lefthook.yml'),
    writes('commitlint.config.ts', 'commitlint.config.ts'),
    writes('probity.config.ts', 'probity.config.ts'),
    writes('mise.toml', 'mise.toml'),
    writes('gitleaks.toml', '.gitleaks.toml'),
    writes('vale.ini', '.vale.ini'),
    writes('vale-styles/NoEmDash.yml', '.vale/styles/ket/NoEmDash.yml'),
    writes('vale-styles/Terminology.yml', '.vale/styles/ket/Terminology.yml'),
    writes('vale-styles/Intensifiers.yml', '.vale/styles/ket/Intensifiers.yml'),
    writes('vale-styles/WeakOpeners.yml', '.vale/styles/ket/WeakOpeners.yml'),
    writes('vale-vocabulary/accept.txt', '.vale/styles/config/vocabularies/ket/accept.txt'),
    writes('gitignore', '.gitignore'),
    writes('skills-lock.json', 'skills-lock.json'),
    writes('CLAUDE.md', 'CLAUDE.md'),
    writes('github-ci.yml', '.github/workflows/ci.yml'),
    writes('source/router.tsx', 'src/app/router.tsx'),
    writes('source/routeTree.gen.ts', 'src/app/routeTree.gen.ts'),
    writes('source/routes/__root.tsx', 'src/app/routes/__root.tsx'),
    writes('source/routes/index.tsx', 'src/app/routes/index.tsx'),
    writes('source/greeting/model/greeting.ts', 'src/entities/greeting/model/greeting.ts'),
    writes(
      'source/greeting/model/greeting.test.ts',
      'src/entities/greeting/model/greeting.test.ts',
    ),
    writes(
      'source/greeting/model/greeting.property.test.ts',
      'src/entities/greeting/model/greeting.property.test.ts',
    ),
    writes('source/greeting/ui/greeting-panel.tsx', 'src/entities/greeting/ui/greeting-panel.tsx'),
    writes('source/greeting/index.ts', 'src/entities/greeting/index.ts'),
    writes('source/e2e/greeting.spec.ts', 'e2e/greeting.spec.ts'),
  ],
  integrations: [
    {
      name: 'mobbin',
      asks: 'mobbin is a gallery of shipped screens to design against. A seat costs the same whether the repository is public or private.',
      reaches: { stage: 'designing', reference: 'https://mobbin.com' },
    },
    {
      name: 'codecov',
      asks: 'codecov, coverage on each pull request. Free on a public repository, paid on a private one past 250 uploads a month.',
      files: [writes('github-coverage.yml', '.github/workflows/coverage.yml')],
    },
    {
      name: 'codeql',
      asks: 'codeql, security scanning on each push. Free on a public repository, paid on a private one per committer.',
      files: [writes('github-codeql.yml', '.github/workflows/codeql.yml')],
    },
    {
      name: 'coderabbit',
      asks: 'coderabbit, a review on each pull request. Free on a public repository, 200 private reviews a month, then paid.',
      files: [writes('coderabbit.yaml', '.coderabbit.yaml')],
    },
  ],
};
