import type { PresetItem } from '@ket/preset';

import {
  copies,
  STANDING_FILES,
  STANDING_INTEGRATIONS,
  STANDING_TOOLCHAIN,
  writes,
} from '@ket/preset';

export const WEB_PRESET: PresetItem = {
  $schema: 'https://ui.shadcn.com/schema/registry-item.json',
  name: 'ket-web',
  type: 'registry:item',
  title: 'ket web',
  description:
    'A TanStack Start application under ket, with the gate chain ket runs against itself.',
  dependencies: [
    '@base-ui/react@1.6.0',
    '@tanstack/react-router@1.170.18',
    '@tanstack/react-start@1.168.34',
    'class-variance-authority@0.7.1',
    'clsx@2.1.1',
    'tailwind-merge@3.6.0',
    'react@19.2.8',
    'react-dom@19.2.8',
    'varlock@1.16.0',
  ],
  devDependencies: [
    ...STANDING_TOOLCHAIN,
    '@varlock/vite-integration@1.4.0',
    'oxlint-plugin-react-doctor@0.9.3',
    'msw@2.15.0',
    'tailwindcss@4.3.3',
    '@tailwindcss/vite@4.3.3',
    'oxlint-tailwindcss@1.6.0',
    'vite@8.2.0',
    '@vitejs/plugin-react@6.0.5',
    '@playwright/test@1.62.1',
    'playwright-bdd@9.2.0',
    '@axe-core/playwright@4.12.1',
    'steiger@0.6.0',
    '@feature-sliced/steiger-plugin@0.7.0',
    '@steiger/toolkit@0.2.3',
    '@types/react@19.2.18',
    '@types/react-dom@19.2.4',
    '@fontsource-variable/google-sans-flex@5.3.1',
    '@fontsource-variable/google-sans-code@5.3.0',
    'storybook@10.5.5',
    '@storybook/tanstack-react@10.5.5',
    '@storybook/addon-a11y@10.5.5',
    '@vitest/browser-playwright@4.1.10',
    'vitest-browser-react@2.2.0',
    'dependency-cruiser@18.1.1',
  ],
  files: [
    ...STANDING_FILES,
    writes('CLAUDE.plain.md', 'CLAUDE.plain.md'),
    writes('vite.config.ts', 'vite.config.ts'),
    writes('playwright.config.ts', 'playwright.config.ts'),
    writes('steiger.config.ts', 'steiger.config.ts'),
    writes('dependency-cruiser.cjs', '.dependency-cruiser.cjs'),
    writes('components.json', 'components.json'),
    writes('bunfig.toml', 'bunfig.toml'),
    writes('source/env.schema', '.env.schema'),
    writes('source/env.d.ts', 'env.d.ts'),
    writes('source/shared/cn.ts', 'src/shared/cn.ts'),
    writes('source/shared/cn.test.ts', 'src/shared/cn.test.ts'),
    writes('source/shared/ui/button.tsx', 'src/shared/ui/button.tsx'),
    writes('source/shared/ui/button.stories.tsx', 'src/shared/ui/button.stories.tsx'),
    writes('source/shared/ui/button.browser.test.tsx', 'src/shared/ui/button.browser.test.tsx'),
    writes('source/shared/ui/badge.tsx', 'src/shared/ui/badge.tsx'),
    writes('source/shared/ui/badge.stories.tsx', 'src/shared/ui/badge.stories.tsx'),
    writes('source/shared/ui/badge.browser.test.tsx', 'src/shared/ui/badge.browser.test.tsx'),
    writes('source/styles.css', 'src/app/styles.css'),
    writes('source/router.tsx', 'src/app/router.tsx'),
    writes('source/routeTree.gen.ts', 'src/app/routeTree.gen.ts'),
    writes('source/routes/__root.tsx', 'src/app/routes/__root.tsx'),
    writes('source/routes/index.tsx', 'src/app/routes/index.tsx'),
    writes('source/welcome/model/welcome.ts', 'src/entities/welcome/model/welcome.ts'),
    writes('source/welcome/model/welcome.test.ts', 'src/entities/welcome/model/welcome.test.ts'),
    writes(
      'source/welcome/model/welcome.property.test.ts',
      'src/entities/welcome/model/welcome.property.test.ts',
    ),
    writes('source/welcome/api/welcomed.ts', 'src/entities/welcome/api/welcomed.ts'),
    writes(
      'source/welcome/api/welcomed.integration.test.ts',
      'src/entities/welcome/api/welcomed.integration.test.ts',
    ),
    writes('source/test-support/network.ts', 'src/test-support/network.ts'),
    writes('source/test-support/integration-setup.ts', 'src/test-support/integration-setup.ts'),
    writes('source/welcome/ui/welcome-heading.tsx', 'src/entities/welcome/ui/welcome-heading.tsx'),
    writes(
      'source/welcome/ui/welcome-heading.stories.tsx',
      'src/entities/welcome/ui/welcome-heading.stories.tsx',
    ),
    writes(
      'source/welcome/ui/welcome-heading.browser.test.tsx',
      'src/entities/welcome/ui/welcome-heading.browser.test.tsx',
    ),
    writes('source/welcome/index.ts', 'src/entities/welcome/index.ts'),
    writes('source/e2e/helpers/a11y.ts', 'e2e/helpers/a11y.ts'),
    writes('source/e2e/helpers/harness.ts', 'e2e/helpers/harness.ts'),
    writes('source/features/welcome.feature', 'features/welcome.feature'),
    writes('source/e2e/steps/welcome.steps.ts', 'e2e/steps/welcome.steps.ts'),
    writes('source/storybook/main.ts', '.storybook/main.ts'),
    writes('source/storybook/preview.ts', '.storybook/preview.ts'),
    writes('source/scripts/check-ui-pairs.mts', 'scripts/check-ui-pairs.mts'),
    writes('source/scripts/check-env.mts', 'scripts/check-env.mts'),
    writes('source/scripts/bdd-binding.mts', 'scripts/bdd-binding.mts'),
    writes('source/scripts/check-bdd-binding.mts', 'scripts/check-bdd-binding.mts'),
    writes('source/scripts/protect-generated.mts', 'scripts/protect-generated.mts'),
    copies('source/hero/ket-bg.mp4', 'public/ket-bg.mp4'),
    copies('source/hero/ket-bg-poster.webp', 'public/ket-bg-poster.webp'),
  ],
  integrations: [
    {
      name: 'mobbin',
      category: 'design reference',
      asks: 'mobbin is a gallery of shipped screens to design against. A seat costs the same whether the repository is public or private.',
      reaches: { stage: 'designing', reference: 'https://mobbin.com' },
      mcp: [{ name: 'mobbin', url: 'https://api.mobbin.com/mcp' }],
    },
    {
      name: 'chromatic',
      category: 'visual review',
      asks: 'chromatic reviews what a page looks like on each push. Free to 5000 snapshots a month on a public repository or a private one, then paid.',
      installs: ['chromatic@18.1.0', '@chromatic-com/playwright@0.14.11'],
      skills: [
        { name: 'chromatic-setup-ci', source: 'chromaui/chromatic-skills' },
        { name: 'chromatic-workflow-debug', source: 'chromaui/chromatic-skills' },
      ],
      files: [
        writes('github-chromatic.yml', '.github/workflows/chromatic.yml'),
        writes('source/chromatic/harness.ts', 'e2e/helpers/harness.ts'),
        writes('source/chromatic/check-bdd-binding.mts', 'scripts/check-bdd-binding.mts'),
      ],
    },
    {
      name: 'scorecard',
      category: 'supply chain',
      asks: 'scorecard publishes a supply-chain risk score on each push to main and once a week. A public repository gets the full score; a private one needs GitHub Advanced Security before scorecard can publish anything.',
      files: [writes('github-scorecard.yml', '.github/workflows/scorecard.yml')],
    },
    ...STANDING_INTEGRATIONS,
  ],
};
